### ISSUE TITLE
Verify Ilastik performance

### ISSUE THREAD

**Issue by wrgr** [aplbrain/saber#1]
Seems to be some version incompatibilities.  To provide additional debug information as it becomes available

**Comment by erikjohnson24** [comment]
Closing as ilastik versions appear to be resolved.

**Comment by dii-gineer** [comment]
![Captura de pantalla 2019-05-07 a la(s) 2 46 50 PM](https://user-images.githubusercontent.com/20343916/57328531-489c6780-70d7-11e9-9854-db669e9fa298.png)
Hi! Im still getting the error related to this.  How can I fix it?
