### ISSUE TITLE
Grid Sampler for New Optimize Sampler API

### ISSUE THREAD

**Issue by erikjohnson24** [aplbrain/saber#35]
We need to update the grid sampler for the new optimization format. 
The sampler here 
https://github.com/aplbrain/saber/blob/development/conduit/conduit
if args.sampling_strategy == 'random':
Should allow for a 'grid' as well. 
Here, implement a grid sampler
https://github.com/aplbrain/saber/blob/development/conduit/utils/parameterization.py
Which steps through the jobs in order.

**Comment by dxenes1** [comment]
Added in https://github.com/aplbrain/saber/pull/34
